- name: Install PostgreSQL dependencies
  action: apt pkg={{ item }} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.3 state=latest update_cache=true

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf

- name: Restart PostgreSQL
  command: service postgresql restart

- name: Ensure database is created
  postgresql_db: name={{ db_name }}
  sudo: yes
  sudo_user: postgres

- name: Ensure user has access to database
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL
  sudo: yes
  sudo_user: postgres

- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{ db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: yes
  sudo_user: postgres
